import type { Blueprint } from '@seamapi/blueprint'

import { type CommandSpec, getCommandSpec } from '../command-spec.js'
import { renderBashCompletion } from './render-bash.js'
import { renderFishCompletion } from './render-fish.js'
import { renderZshCompletion } from './render-zsh.js'

export const completionShells = ['bash', 'fish', 'zsh'] as const

export type CompletionShell = (typeof completionShells)[number]

export const isCompletionShell = (shell: unknown): shell is CompletionShell =>
  completionShells.includes(shell as CompletionShell)

/** File name to install the completion script for each shell as. */
export const completionFileNames: Record<CompletionShell, string> = {
  bash: 'seam.bash',
  fish: 'seam.fish',
  zsh: 'seam.zsh',
}

const renderers: Record<CompletionShell, (spec: CommandSpec) => string> = {
  bash: renderBashCompletion,
  fish: renderFishCompletion,
  zsh: renderZshCompletion,
}

export const renderCompletion = (
  shell: CompletionShell,
  blueprint: Blueprint,
): string => renderers[shell](getCommandSpec(blueprint))

/**
 * Render the completion loader installed by system packages.
 *
 * The loader runs 'seam completion' the first time the shell completes a seam
 * command, so installed completions always match the CLI's current Seam API
 * definitions instead of the definitions packaged at release time. Each shell
 * loads its completion file on demand, so the CLI runs once per shell session
 * at first completion, never at shell startup.
 *
 * The loader degrades to no completions when the seam command is missing or
 * cannot produce a script, e.g., offline before the definitions are cached.
 */
export const renderCompletionStub = (shell: CompletionShell): string =>
  stubs[shell]

const stubHeader = (shell: CompletionShell): string =>
  `# ${shell} completion loader for the seam command.
#
# Generated by @seamapi/cli. Loads completions from the CLI on first use, so
# they always match the CLI's current Seam API definitions. Requires the seam
# command on PATH. Print the underlying script with 'seam completion ${shell}'.`

const stubs: Record<CompletionShell, string> = {
  bash: `${stubHeader('bash')}
#
# Install to /usr/share/bash-completion/completions/seam

if command -v seam > /dev/null 2>&1; then
  eval "$(seam completion bash 2> /dev/null)"
fi
`,
  fish: `${stubHeader('fish')}
#
# Install to /usr/share/fish/vendor_completions.d/seam.fish

if command --query seam
    seam completion fish 2> /dev/null | source
end
`,
  zsh: `#compdef seam
${stubHeader('zsh')}
#
# Install to a directory in fpath as _seam

# The generated script ends by dispatching on funcstack, so evaluating it
# while this autoloaded _seam runs both redefines _seam and completes the
# in-flight request.
eval "$(seam completion zsh 2> /dev/null)"
`,
}
